name: Lint - YAML

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-yamllint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: install yamllint
      run: pip install -r ./build/yamllint-requirements.txt --require-hashes

    - name: run yamllint
      run: yamllint --no-warnings .
